// ===========================================
// Message Model
// Defines the schema for chat messages
// ===========================================

const mongoose = require('mongoose');

// Define the Message schema
const messageSchema = new mongoose.Schema({
    // Who sent the message
    senderId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Sender is required']
    },

    // Who receives the message
    receiverId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: [true, 'Receiver is required']
    },

    // The actual message content
    message: {
        type: String,
        default: '',
        trim: true,
        maxlength: [5000, 'Message cannot exceed 5000 characters']
    },

    // Type of message: text, image, file, voice, gif, video, videoNote, location, liveLocation
    type: {
        type: String,
        enum: ['text', 'image', 'file', 'voice', 'gif', 'video', 'videoNote', 'location', 'liveLocation'],
        default: 'text'
    },

    // For media messages, store the file path
    filePath: {
        type: String,
        default: ''
    },

    // Original file name (for file uploads)
    fileName: {
        type: String,
        default: ''
    },

    // File size in bytes
    fileSize: {
        type: Number,
        default: 0
    },

    // Duration for voice/video messages (in seconds)
    duration: {
        type: Number,
        default: 0
    },

    // Voice message transcription (speech-to-text)
    transcription: {
        text: {
            type: String,
            default: null
        },
        status: {
            type: String,
            enum: ['pending', 'processing', 'completed', 'failed', 'not_available'],
            default: null
        },
        processedAt: {
            type: Date,
            default: null
        },
        error: {
            type: String,
            default: null
        }
    },

    // GIF URL or sticker ID
    gifUrl: {
        type: String,
        default: ''
    },

    // Sound URL for GIF stickers
    soundUrl: {
        type: String,
        default: ''
    },

    // Location data (for location and liveLocation types)
    location: {
        latitude: {
            type: Number,
            default: null
        },
        longitude: {
            type: Number,
            default: null
        },
        accuracy: {
            type: Number,
            default: null
        },
        address: {
            type: String,
            default: ''
        }
    },

    // Live location specific fields
    liveLocationDuration: {
        type: Number, // Duration in minutes (15, 60, 480)
        default: 0
    },
    liveLocationExpiresAt: {
        type: Date,
        default: null
    },
    liveLocationActive: {
        type: Boolean,
        default: false
    },

    // Has the receiver seen this message?
    seen: {
        type: Boolean,
        default: false
    },

    // Has the message been delivered to receiver's device?
    delivered: {
        type: Boolean,
        default: false
    },

    // When was the message delivered
    deliveredAt: {
        type: Date,
        default: null
    },

    // When was the message seen
    seenAt: {
        type: Date,
        default: null
    },

    // Is message edited?
    isEdited: {
        type: Boolean,
        default: false
    },

    // When was the message edited
    editedAt: {
        type: Date,
        default: null
    },

    // Is message unsent (completely removed)?
    isUnsent: {
        type: Boolean,
        default: false
    },

    // Is message deleted for both (shows "message was deleted")?
    isDeleted: {
        type: Boolean,
        default: false
    },

    // Deleted for specific users (delete for me)
    deletedFor: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    }],

    // Message reactions (emoji reactions from users)
    reactions: [{
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true
        },
        emoji: {
            type: String,
            required: true
        },
        createdAt: {
            type: Date,
            default: Date.now
        }
    }],

    // Disappearing message settings
    isDisappearing: {
        type: Boolean,
        default: false
    },

    // Generated by Silent Care Mode auto-reply
    isAutoReply: {
        type: Boolean,
        default: false
    },

    // Time in milliseconds until message disappears (10000, 60000, 3600000)
    disappearAfter: {
        type: Number,
        default: null
    },

    // When the message will be deleted
    expiresAt: {
        type: Date,
        default: null
    },

    // When the message was sent
    createdAt: {
        type: Date,
        default: Date.now
    }
});

// ===========================================
// Indexes
// For faster queries when fetching chat history
// ===========================================

// Index for finding messages between two users
messageSchema.index({ senderId: 1, receiverId: 1 });

// Index for sorting by creation time
messageSchema.index({ createdAt: -1 });

// TTL index for disappearing messages - MongoDB auto-deletes when expiresAt is reached
messageSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 0 });

// Create and export the model
const Message = mongoose.model('Message', messageSchema);

module.exports = Message;
